#!/usr/bin/bash

set -e
set -x

script_path=$(readlink -f "$0")
base_dir=$(dirname "$script_path")
conf_dir="$base_dir/conf"
tools_dir="$base_dir/tools"
sysroot_dir="$base_dir/sysroot"
stamps_dir="$base_dir/stamps"
host=x86_64-unknown-linux-gnu
target=i686-unknown-linux-gnu

build_auto() {
    if [ -f configure ]; then
        configure=configure
    else
        configure=autogen.sh
    fi

    ./$configure $@ --prefix=/usr --host=$target --build=$host

    make
    make install DESTDIR="$sysroot_dir"
}

build_crosstool-ng() {
    ./bootstrap
    ./configure --enable-local
    make

    cp "$conf_dir"/crosstool-ng .config

    ./ct-ng build

    cp -a "$tools_dir"/$target/sysroot/* "$sysroot_dir"
}

build_ncurses() {
    build_auto --without-ada
}

build_bash() {
    build_auto
}

build_wayland() {
    build_auto
}

build_module() {
    if [ ! -f "$stamps_dir"/$1 ]; then
        pushd $1
        build_$1
        popd

        touch "$stamps_dir"/$1
    fi
}

mkdir -p "$stamps_dir"

build_module crosstool-ng

export PATH="$tools_dir"/bin:$PATH
export CC="$target-gcc --sysroot=$sysroot_dir"
export LD="$target-ld --sysroot=$sysroot_dir"
export MAKEFLAGS=-j8

for module in ncurses bash wayland
do
    build_module $module
done

